name: Questions about the plugin
description: If you have a question about the plugin or how to use it, please do ask here. If you have multiple disjoint questions, please open additional issues.
labels: ["question"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! Please read all prompts on this page carefully and make sure that you have entered the relevant details **before** submitting.
  - type: checkboxes
    id: terms
    attributes:
      label: Update disclaimer
      description: If the game recently updated, XIVLauncher and plugins will not work. They need to be updated first. You can get notified about updates on our Discord.
      options:
        - label: Yes, I have checked and my request is not related to the game updating and plugins not working correctly.
          required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Where are you running XIVLauncher?
      options:
        - Applies to all
        - Windows
        - Linux
        - macOS
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Ask your question here
      description: Please ask your question here.
      placeholder: Tell us what you did!
    validations:
      required: true
